#!/usr/bin/env python3

import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored


def main():
    
    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screen_name_of_user")
        
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    
    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)

    # Gets user timeline and saves it in a list of strings
    timeline = helpers.get_user_timeline(sys.argv[1])
    
    # If invalid twitter handle, throw an error message
    if timeline is None:
        print("Invalid user")
        return 0
    
    # iterates through elements in list and analyzes the strings therein
    for i in range(100):
        
        score = analyzer.analyze(timeline[i])
        
        if score > 0.0:
            print(colored(str(score) + " " + (timeline[i]), "green"))
            
        elif score < 0.0:
            print(colored(str(score) + " " + (timeline[i]), "red"))
            
        else:
            print(colored(str(score) + " " + (timeline[i]), "yellow"))
            
    
if __name__ == "__main__":
    main()    
